[package]
name = "tls_garble"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
garble_lang = "0.2.0"
hex = "0.4.3"
